# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
