# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatbuffer_onlineusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbuffer',
            name='userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
